"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""

from dbal.group import Group


class _GroupsDao:

    def __init__(self, ds):
        self.ds = ds

    def create_group(self, p):
        """
        (C)RUD: groups
        Generated values are passed to DTO.
        :param p: Group
        :return: None
        :raises Exception: if no rows inserted.
        """
        self.ds.create_one(p)

    def read_group(self, g_id):
        """
        C(R)UD: groups
        :param g_id: int
        :return: Group
        :raises Exception: if amount of returned rows != 1.
        """
        return self.ds.read_one(Group, {'g_id': g_id})

    def update_group(self, g_id, data):
        """
        CR(U)D: groups
        :param g_id: int
        :param data: dict of pairs column-value
        :return: int (the number of affected rows)
        """
        self.ds.update_one(Group, data, {'g_id': g_id})

    def delete_group(self, g_id):
        """
        CRU(D): groups
        :param g_id: int
        :return: int (the number of affected rows)
        """
        return self.ds.delete_one(Group, {'g_id': g_id})
