"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""

from .data_store import *


class Group(Base):
    __tablename__ = 'groups'

    g_id = Column('g_id', Integer, primary_key=True, autoincrement=True)
    g_name = Column('g_name', String(65535), index=True, unique=True)
