"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""

from .data_store import *


class GroupLi(Base):
    __abstract__ = True

    g_id = Column('g_id', autoincrement=True)
    g_name = Column('g_name')
    g_tasks_count = Column('g_tasks_count')

    SQL = """select g.*,  
                (select count(*) from tasks where g_id=g.g_id) as g_tasks_count 
                from groups g 
                order by g.g_id"""
