"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""

from .data_store import *


class ProjectLi(Base):
    __abstract__ = True

    p_id = Column('p_id', autoincrement=True)
    p_name = Column('p_name')
    p_tasks_count = Column('p_tasks_count')

    SQL = """select p.*, 
                (select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
                from projects p 
                order by p.p_id"""
